### ISSUE TITLE
Question: Why not using tonic?

### ISSUE THREAD

**Issue by algermissen** [mozilla-services/google-cloud-rust#16]
Hi,

so glad to see this finally happening! Thank you so much.

One question: I see you are using https://crates.io/crates/grpcio/0.9.0  for the grpc connector. I am curious: why did you not choose tokio / tonic[1]?

Jan

[1] https://github.com/hyperium/tonic

**Comment by pjenvey** [comment]
Despite google-cloud-rust just going public, this crate sort of predated tonic -- there was tower-grpc (tonic before it was renamed) at the time but it wasn't as mature as tonic is now.

Also the underlying grpc.io bits are well proven.
